### PR TITLE
test(paragraph): simplify paragraph benchmarks

### PR DESCRIPTION
**Pull request by joshka**
Reduce benchmarks from 60 calls to 18. Now 3 different line counts
(64, 2048, 65535) * 6 different tests (new, render, scroll half / full,
wrap, wrap and scroll)

image

image

### CODE REVIEW

**Comment by joshka** [comment]
@haydenflinner given you're recently been benchmarking, do these look a little better to you?

**Comment by haydenflinner** [comment]
Yep, looks good to me! I was surprised at how many paragraph benches there were, prior. This looks more representative too.

**Review by mindoodoo — APPROVED** [review]
Looks so much better, thanks a lot for this man !

Out of curiosity, do you know what made the code coverage regress a little bit `src/widget/mod.rs` ?

**Review by orhun — APPROVED** [review]

**Comment by joshka** [comment]
> Out of curiosity, do you know what made the code coverage regress a little bit src/widget/mod.rs ?

Looking at https://app.codecov.io/gh/tui-rs-revival/ratatui/pull/282/indirect-changes?src=pr&el=tree-more, it suggests that we probably don't have a test case for one branch of the `Debug` impl on `Borders` (which wasn't tested by this code 🤷‍♂️).

**Pull request merged**
