### PR TITLE
feat(stylize): allow all widgets to be styled

### PR DESCRIPTION
**Pull request by joshka**
This PR:
- renames the underlined and dimmed methods to match the Style consts (underline and dim)
- adds `Stylize` implementations for all the remaining widgets 
- Implements stylized for Style enabling. E.g.: `Style::new().blue()`
- Makes it possible to remove modifiers. E.g.: `Style::new().not_bold()`
- Documents the changes
- Simplifies the Stylize macros

Details:
- Add styled impl to:
  - Barchart
  - Chart (including Axis and Dataset),
  - Guage and LineGuage
  - List and ListItem
  - Sparkline
  - Table, Row, and Cell
  - Tabs
  - Style
- Allow modifiers to be removed (e.g. .not_italic())
- Allow .bg() to recieve Into<Color>
- Made shorthand methods consistent with modifier names (e.g. dim() not
  dimmed() and underlined() not underline())
- Simplify integration tests
- Add doc comments
- Simplified stylize macros with https://crates.io/crates/paste

### CODE REVIEW

**Comment by joshka** [comment]
Pinging @samyosm for a review on this as a  follow up on https://github.com/tui-rs-revival/ratatui/pull/283

**Comment by orhun** [comment]
I thought we were putting macro code behind `macros` feature but that's only for user-facing changes, right?

**Comment by joshka** [comment]
> I thought we were putting macro code behind `macros` feature but that's only for user-facing changes, right?

Yep. Just user facing macros makes sense. Here they cut down on hundreds of LoC so that’s really useful.

**Comment by joshka** [comment]
(rebased on main)

**Comment by joshka** [comment]
Rebased on main to resolve conflicts with prelude introduction and barchart changes (barchart.rs -> barchart/mod.rs).

**Review by sayanarijit — APPROVED** [review]

**Comment by sayanarijit** [comment]
This is cool...

**Comment by joshka** [comment]
Fixed up doc tests problem that I introduced by adding more docs.

**Review by mindoodoo — APPROVED** [review]

**Pull request merged**
