### PR TITLE
feat(terminal): expose 'swap_buffers' method

### PR DESCRIPTION
**Pull request by Philipp-M**
I needed raw access to clearing/swapping the buffers, I think it doesn't hurt to expose this functionality.

### CODE REVIEW

**Comment by joshka** [comment]
Can you tell us more about the use case for this?

**Comment by Philipp-M** [comment]
Actually I'm currently prototyping a TUI implementation of the xilem architecture (not yet open source, since the code base is still quite messy, but I'll open source it soon).

I thought about writing my own double-buffered crossterm-based backend, but after looking a little bit through the buffer implementation of ratatui, I noticed how many things have to be considered to get it right (grapheme widths, drawing order, minimal update sequence to stdout etc.) that I decided for now to "abuse" it as backend for drawing directly into the framebuffer and manually flush and swap buffers, to have more time focusing on the higher level parts of the framework/architecture (widgets, event-flow, async etc.).

**Comment by joshka** [comment]
Sounds good. Can you please write a quick unit test (in `terminal.rs`) for this.
A lot of the tests generally are in the tests/ folder, but it's worthwhile having small targeted tests in a tests submodule (ala https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html)

**Comment by Philipp-M** [comment]
Is this enough?

**Review by joshka — APPROVED** [review]
LGTM

**Comment by joshka** [comment]
I'm just checking in with the other maintainers that there isn't anything obviously wrong with making this public.

**Comment by sayanarijit** [comment]
LGTM

**Review by sayanarijit — APPROVED** [review]

**Pull request merged**
