### PR TITLE
feat(block): support placing the title on bottom

### PR DESCRIPTION
**Pull request by orhun**
> Upstream: [#669](https://github.com/fdehau/tui-rs/pull/669)

## Description

Before you could only put the title on the top row of a block.  Now you can put it on the bottom row! Revolutionary.

In the future, implementing an option for both a bottom and top title is possible, but seems unnecessary considering you could just manually have a `Layout` and do the work yourself at that point, and having support for title wizardry seems pointless.  The farthest you could go is having an option to actually move the title everywhere; it's an easy extension and seems like something that would normally be built-in.  Hence here it is; you can do top and bottom, left right and center.

## Testing guidelines

When creating a `Block` with, say, `Block::default().title()`, slap on a `.title_on_bottom()`.  Check `tests/widget_block.rs` for the tests, which are just a copy of the alignment tests.

## Checklist

* [x] I have read the [contributing guidelines](../CONTRIBUTING.md).
* [x] I have added relevant tests.
* [x] I have documented all new additions.

### CODE REVIEW

**Comment by mindoodoo** [comment]
@rabirabirara The test you added seems to be failing.

**Comment by Benjscho** [comment]
I have a fix for the tests added, appears the expected behaviors were incorrectly input. Added a pull request for the branch here so this can be merged: https://github.com/tui-rs-revival/ratatui/pull/88

**Comment by sayanarijit** [comment]
Merged #88 to this branch, however, note that since it's a new feature, it's still out of scope for the initial release.

**Review by mindoodoo — APPROVED** [review]

**Comment by mindoodoo** [comment]
Seems like a small useful feature, I'm in favor of adding it in. Thoughts @sayanarijit @orhun ?

**Comment by orhun** [comment]
Yup, I agree. (_approved_)

**Comment by Xithrius** [comment]
Thank you for doing this PR! (Am author of https://github.com/fdehau/tui-rs/issues/625)

**Pull request merged**
