### PR TITLE
docs(color): parse more color formats and add docs

### PR DESCRIPTION
**Pull request by joshka**
Fixes https://github.com/tui-rs-revival/ratatui/issues/305

### CODE REVIEW

**Comment by joshka** [comment]
# Doc Preview:

image

...

image

...

image

...

image

...

image

**Review by mindoodoo — APPROVED** [review]

**Comment by joshka** [comment]
@orhun there are existing tests for the invalid formats - am I misunderstanding what you're asking for here?

https://github.com/joshka/ratatui/blob/f100d222c962de59c23ee964be4cfe78c601d2d3/src/style.rs#L578-L593

**Comment by orhun** [comment]
Everything is okay as far as we cover these changes I think:

https://github.com/joshka/ratatui/blob/f100d222c962de59c23ee964be4cfe78c601d2d3/src/style.rs#L421-L430

**Comment by joshka** [comment]
Force push updates the tests to cover more happy paths and a few useful error paths, and moves the aliases out of the match into the replacements only.

**Review by orhun — APPROVED** [review]

**Pull request merged**
