### PR TITLE
style: reformat imports

### PR DESCRIPTION
**Pull request by joshka**
Order imports by std, external, crate and group them by crate

### CODE REVIEW

**Comment by sayanarijit** [comment]
Looks like it will create merge conflict with other PRs. LGTM, otherwise.

**Review by sayanarijit — APPROVED** [review]

**Comment by joshka** [comment]
Yup. I figured that a rebase would be necessary depending on which PR goes first regardless.

**Comment by sayanarijit** [comment]
I guess it's easy to force rebase this pr than other prs, so let's wait for a good opportunity.

**Comment by joshka** [comment]
I'm not sure I'd worry too much about waiting - there's always going to be some amount of outstanding PRs, so there's not really a good or a bad time to merge cross repo type stuff.

This contains a [rustfmt.toml](https://github.com/tui-rs-revival/ratatui/pull/219/files#diff-a947c9d2523f34e53b9cdcd6411174a3148f23ea03ad8a61c1aee7b3ea005440) change that make all the changes automatic.

There are 2 ways to make the pain of rebasing on top of this pain free (assuming this change gets merged before some other PR):
1. If you're squashing the PR, `git checkout main -- rustfmt.toml; cargo fmt; git add src; git commit -m 'style: reformat'` then squash and rebase.
2. More difficult: rebase and sort out the conflcts then cargo fmt.

Option 1 would be mostly automatic.

**Comment by joshka** [comment]
Rebased and fixed conflict in `rustfmt.toml`

**Review by sayanarijit — APPROVED** [review]

**Pull request merged**
