### PR TITLE
refactor(text): simplify reflow implementation

### PR DESCRIPTION
**Pull request by joshka**
This is a PR that extracts the refactor part of https://github.com/tui-rs-revival/ratatui/pull/259, as well as the code for Line->StyledGrapheme. It's intent is to make the review of the actual wrapping code easier. It contains the following commits from 259:
## refactor(text): split text::* into separate files (47f8c815cec4480b27606916af07361c662bd433)
- https://github.com/tui-rs-revival/ratatui/pull/259/commits/cf4f0ed391bc5c789ae3e7b823e5005b68b14c81:  refactor(text): reorganize text module items into their own files 
- does not include wrap.rs

## feat(text): expose graphemes on Line (ec411bb1cd113efb05174f68d59b0795fd7ae7e4)
- add `Line::styled()`
- add `Line::styled_graphemes()`
- add `StyledGrapheme::new()`

which contains
  - https://github.com/tui-rs-revival/ratatui/pull/259/commits/54aac9148afc0b02d6fae20391ed0d1e7f772bee:  feat(text): add Line::styled() and Line.styled_graphemes() 
  - https://github.com/tui-rs-revival/ratatui/pull/259/commits/c1f3cf83d9e893841c1d33512513988c79445f18:  chore: add doc comment description to StyledGrapheme 
  - https://github.com/tui-rs-revival/ratatui/pull/259/commits/66706c65faab8b373afdd6e76dc1ec6946b69445:  fix: remediate lifetime and Cow issues in Line

and adds:
- impl `Styled` for `StyledGrapheme` from #283
- `StyledGrapheme::new()` to make the test / docs neater

# Review approach
The new code is called out above - no need to review the entire PR, just the bits called out.
Pinging @lthoerner for 👀 
The rest of #289 will be rebased on top of this, but this part should be merged quickly to avoid more drift.

### CODE REVIEW

**Comment by joshka** [comment]
Formatting issue is unrelated to this - seems like a slight change in the current nightly toolchain

**Review by mindoodoo — APPROVED** [review]
Needs to be rebased, otherwise lgtm, thanks @joshka for extracting this and thanks @lthoerner for taking this much needed task on !

**Comment by joshka** [comment]
This is @lthoerner's work. I just git-monkied it. Will rebase and merge soon. Likely after the release to give it some time to bake.

**Comment by joshka** [comment]
rebased on main - requires a re-review as there was a conflict in the rebase in comments in text.rs for `Span` (which are then changed in the second commit), and in the set_style() method in text.rs for `Span`.

**Review by mindoodoo — APPROVED** [review]

**Review by orhun — APPROVED** [review]

**Comment by orhun** [comment]
I recommend updating the commit message to something like `refactor(text): simplify reflow implementation` or something like that before merging.

**Comment by joshka** [comment]
yes - the goal on this was to cut down the size of the diff in #259 to something more reviewable. I'd want to take a second step that's similar - find some parts of the rest that are easy to see are useful steps along the way to the implementation that help someone review a part at a time rather than 2000+ lines of churn. https://smartbear.com/learn/code-review/best-practices-for-peer-code-review/ is a helpful article on why.

**Comment by lthoerner** [comment]
Should we update the changelog and the title of the PR then?

**Comment by joshka** [comment]
The changelog is automatically updated as part of the release process generally.
This PR is merged so changing anything on it won't have any meaningful effect.

**Pull request merged**
