### PR TITLE
chore(release): prepare for 0.21.0

### PR DESCRIPTION
**Pull request by orhun**

### CODE REVIEW

**Comment by Eyesonjune18** [comment]
Can we wait for #193 before releasing 0.21.0?

**Comment by orhun** [comment]
Sure!

**Review by joshka — APPROVED** [review]

**Comment by joshka** [comment]
>Can we wait for https://github.com/tui-rs-revival/ratatui/pull/193 before releasing 0.21.0?

I suspect #193 might take a little bit of time to get over the line. I think we should not rush it, and instead do a small release (either 0.21.1 or 0.22.0) shortly after this.

Behind the scenes on this, about a week ago there were a few PRs that the maintainers talked about as wanting to get in to this release (noteably #12, #183, #180, #11). #149 was on the list as it brings the level of testing of paragraph and reflow up significantly, which makes it easier to develop on top of, and it proved out the Span/Line change we made in #178.

**Comment by Eyesonjune18** [comment]
> I suspect #193 might take a little bit of time to get over the line.

I'll be committing a patch in a few hours, just review it then and see whether it's up to par for this release.

**Review by mindoodoo — APPROVED** [review]

**Review by sayanarijit — APPROVED** [review]

**Comment by Eyesonjune18** [comment]
> I'll be committing a patch in a few hours, just review it then and see whether it's up to par for this release.

Update: I couldn't understand the `WordWrapper.next_line()` implementation from @TimerErTim in order to reflect the same changes in `CharWrapper`. Some help would be much appreciated.

**Comment by TimerErTim** [comment]
> > I'll be committing a patch in a few hours, just review it then and see whether it's up to par for this release.
> 
> Update: I couldn't understand the `WordWrapper.next_line()` implementation from @TimerErTim in order to reflect the same changes in `CharWrapper`. Some help would be much appreciated.

@Eyesonjune18 We can connect on discord. I will reach out to you, since I think you also are on the ratatui server? I'd have time tomorrow and will write you a detailed explanation. We could also setup a call if you desire so.

**Comment by Eyesonjune18** [comment]
> @Eyesonjune18 We can connect on discord. I will reach out to you, since I think you also are on the ratatui server? I'd have time tomorrow and will write you a detailed explanation. We could also setup a call if you desire so.

Yeah, I already DMed you, and I will be available most of this week to set up a time to talk if that works for you.

**Comment by joshka** [comment]
Let's move the chat about the Word wrap to #193

**Comment by orhun** [comment]
I think we're good to go with the release tomorrow. We can incorporate #193 afterwards in a patch/minor version when it is fully ready. 🐻

**Pull request merged**
